/**
 * Data of various boards available for selection
*/
export const boardsData = [
    // 24 boards
    { title: 'Central Board of Secondary Education (CBSE)', value: 'Central Board of Secondary Education (CBSE)' },
    { title: 'Indian Certificate of Secondary Education (ICSE)', value: 'Indian Certificate of Secondary Education (ICSE)' },
    { title: 'Andhra Pradesh Board of Secondary Education (BSEAP)', value: 'Andhra Pradesh Board of Secondary Education (BSEAP)' },
    { title: 'Assam Board of Secondary Education (SEBA)', value: 'Assam Board of Secondary Education (SEBA)' },
    { title: 'Chattisgarh Board of Secondary Education (CGBSE)', value: 'Chattisgarh Board of Secondary Education (CGBSE)'},
    { title: 'Gujarat Secondary and Higher Secondary Education Board (GSEB)', value: 'Gujarat Secondary and Higher Secondary Education Board (GSEB)' },
    { title: 'Haryana Board of School Education (HBSE)', value: 'Haryana Board of School Education (HBSE)'},
    { title: 'Himachal Pradesh Board of School Education (HPBOSE)', value: 'Himachal Pradesh Board of School Education (HPBOSE)'},
    { title: 'Jharkhand Academic Council (JAC)', value: 'Jharkhand Academic Council (JAC)'},
    { title: 'Karnataka Secondary Education Examination Board (KSEEB)', value: 'Karnataka Secondary Education Examination Board (KSEEB)'},
    { title: 'Kerala State Education Board (KBPE)',value: 'Kerala State Education Board (KBPE)'},
    { title: 'Madhya Pradesh Board of Secondary Education (MPBSE)', value: 'Madhya Pradesh Board of Secondary Education (MPBSE)'},
    { title: 'Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)', value: 'Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)'},
    { title: 'Manipur Board of Secondary Education (BSEM)', value: 'Manipur Board of Secondary Education (BSEM)'},
    { title: 'Meghalaya Board of School Education (MBOSE)', value: 'Meghalaya Board of School Education (MBOSE)'},
    { title: 'Mizoram Board of School Education (MBSE)', value: 'Mizoram Board of School Education (MBSE)'},
    { title: 'Nagaland Board of School Education (NBSE)', value: 'Nagaland Board of School Education (NBSE)'},
    { title: 'Odisha Board of Secondary Education (BSE Odisha)', value: 'Odisha Board of Secondary Education (BSE Odisha)'},
    { title: 'Punjab School Education Board (PSEB)', value: 'Punjab School Education Board (PSEB)'},
    { title: 'Rajasthan Board of Secondary Education (RBSE)', value: 'Rajasthan Board of Secondary Education (RBSE)'},
    { title: 'Telangana State Board of Secondary Education (BSETS)', value: 'Telangana State Board of Secondary Education (BSETS)' },
    { title: 'Tamil Nadu Board of Secondary Education (TNBSE)' , value: 'Tamil Nadu Board of Secondary Education (TNBSE)' },
    { title: 'Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)', value: 'Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)'},
    { title: 'West Bengal Board of Secondary Education (WBBSE)', value: 'West Bengal Board of Secondary Education (WBBSE)'}, 
];

export const CBSEdata = [
    {title: 'Arabic', value:'Arabic'},
    {title: 'Assamese' , value:'Assamese'},
    {title: 'Bengali' , value:'Bengali'},
    {title: 'English-Language and Literature' , value:'English-Language and Literature'},
    {title: 'French' , value:'French'},
    {title: 'German' , value:'German'},
    {title: 'Gujarati' , value:'Gujarati'},
    {title: 'Gurung' , value:'Gurung'},
    {title: 'Hindi' , value:'Hindi'},
    {title: 'Japanese' , value:'Japanese'},
    {title: 'Kannada' , value:'Kannada'},
    {title: 'Kashmiri' , value:'Kashmiri'},
    {title: 'Malayalam' , value:'Malayalam'},
    {title: 'Manipuri' , value:'Manipuri'},
    {title: 'Marathi' , value:'Marathi'},
    {title: 'Mizo' , value:'Mizo'},
    {title: 'Odia' , value:'Odia'},
    {title: 'Persian' , value:'Persian'},
    {title: 'Punjabi' , value:'Punjabi'},
    {title: 'Russian' , value:'Russian'},
    {title: 'Sanskrit' , value:'Sanskrit'},
    {title: 'Sindhi' , value:'Sindhi'},
    {title: 'Spanish' , value:'Spanish'},
    {title: 'Tamil' , value:'Tamil'},
    {title: 'Telugu AP' , value:'Telugu AP'},
    {title: 'Telugu Telangana' , value:'Telugu Telangana'},
    {title: 'Tibetian' , value:'Tibetian'},
    {title: 'Urdu' , value:'Urdu'},
    {title: 'Mathematics' , value:'Mathematics'},
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    {title: 'Social Science' , value:'Social Science'},
    {title: 'Art Education' , value:'Art Education'},
];

export const ICSEdata = [
    { title: "English", value: "English" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "French", value: "French" },
    { title: "German", value: "German" },
    { title: "Spanish", value: "Spanish" },
    { title: "History and Civics", value: "History and Civics" },
    { title: "Geography", value: "Geography" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Economics", value: "Economics" },
    { title: "Commercial Studies", value: "Commercial Studies" },
    { title: "Environmental Science", value: "Environmental Science" },
    { title: "Art", value: "Art" },
    { title: "Home Science", value: "Home Science" },
    { title: "Cookery", value: "Cookery" },
    { title: "Fashion Designing", value: "Fashion Designing" },
    { title: "Physical Education", value: "Physical Education" },
    { title: "Yoga", value: "Yoga" },
    { title: "Computer Applications", value: "Computer Applications" },
    { title: "Economic Applications", value: "Economic Applications" },
    { title: "Commercial Applications", value: "Commercial Applications" },
    { title: "Mass Media and Communications", value: "Mass Media and Communications" },
    { title: "Hospitality Management", value: "Hospitality Management" },
];

export const Andhradata = [
    { title: "English", value: "English" },
    { title: "Telugu", value: "Telugu" },
    { title: "Hindi", value: "Hindi" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Urdu", value: "Urdu" },
    { title: "Tamil", value: "Tamil" },
    { title: "Kannada", value: "Kannada" },
    { title: "Oriya", value: "Oriya" },
    { title: "Marathi", value: "Marathi" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Biological Science", value: "Biological Science" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Music", value: "Music" },
    { title: "Computer Science", value: "Computer Science" },
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const Assamdata = [
    { title: "Assamese", value: "Assamese" },
    { title: "Bengali", value: "Bengali" },
    { title: "Hindi", value: "Hindi" },
    { title: "Manipuri", value: "Manipuri" },
    { title: "Mizo", value: "Mizo" },
    { title: "Urdu", value: "Urdu" },
    { title: "Nepali", value: "Nepali" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    // { title: "General Science", value: "General Science" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Science", value: "Social Science" },
    { title: "Computer Science", value: "Computer Science" },
    { title: "Music", value: "Music" },
    { title: "Dance", value: "Dance" },
    { title: "Fine Art", value: "Fine Art" },
    { title: "Weaving and Textile Design", value: "Weaving and Textile Design" },
    { title: "Arabic", value: "Arabic" },
    { title: "Persian", value: "Persian" },
    { title: "Commerce", value: "Commerce" },
    { title: "Yoga and Physical Education", value: "Yoga and Physical Education" }
];

export const Chattisgarhdata = [
    { title: "Bengali", value: "Bengali" },
    { title: "English", value: "English" },
    { title: "Gujarati", value: "Gujarati" },
    { title: "Hindi", value: "Hindi" },
    { title: "Kannada", value: "Kannada" },
    { title: "Malayalam", value: "Malayalam" },
    { title: "Marathi", value: "Marathi" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Punjabi", value: "Punjabi" },
    { title: "Sanskrit", value: "Sanskrit" },
    // { title: "Science", value: "Science" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Science", value: "Social Science" },
    { title: "Tamil", value: "Tamil" },
    { title: "Telugu", value: "Telugu" },
    { title: "Urdu", value: "Urdu" },
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const GujaratData = [
    { title: "Gujarati", value: "Gujarati"},
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const HaryanaData = [
    { title: "Punjabi", value: "Punjabi" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Hindi", value: "Hindi" },
    { title: "Urdu", value: "Urdu" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Agriculture", value: "Agriculture" },
    { title: "Computer Science", value: "Computer Science" },
    { title: "Dance", value: "Dance" },
    { title: "Drawing", value: "Drawing" },
    { title: "Music", value: "Music" },
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const HimachalData = [
    { title: "Hindi", value: "Hindi" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Urdu", value: "Urdu" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Arts", value: "Arts" },
    { title: "Commerce", value: "Commerce" },
    { title: "Computer Science", value: "Computer Science" },
    { title: "Music", value: "Music" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const JharkhandData = [
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Geology", value: "Geology"}, 
    { title: "Social Studies", value: "Social Studies"},
    { title: "Music", value: "Music"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const KarnatakaData = [
    { title: "Kannada", value: "Kannada" },
    { title: "Telugu", value: "Telugu" },
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Marathi", value: "Marathi" },
    { title: "Arabic", value: "Arabic" },
    { title: "Tamil", value: "Tamil" },
    { title: "Urdu", value: "Urdu" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const KeralaData = [
    { title: "Hindi", value: "Hindi" },
    { title: "Malayalam", value: "Malayalam"},
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const MPData = [
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Urdu", value: "Urdu" },
    { title: "Gujrati", value: "Gujrati" },
    { title: "Marathi", value: "Marathi" },
    { title: "Punjabi", value: "Punjabi" },
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const MaharashtraData = [
    { title: "Hindi", value: "Hindi" },
    { title: "Gujarati", value: "Gujarati" },
    { title: "Marathi", value: "Marathi" },
    { title: "Urdu", value: "Urdu" },
    { title: "Bengali", value: "Bengali" },
    { title: "Punjabi", value: "Punjabi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const ManipurData = [
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Manipuri", value: "Manipuri" },
    { title: "Assamese", value: "Assamese" },
    { title: "Bengali", value: "Bengali" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const MeghalayaData = [
    { title: "Hindi", value: "Hindi" },
    { title: "Khasi", value: "Khasi"},
    { title: "Garo", value: "Garo"},
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const MizoramData = [
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mizo", value: "Mizo" },
    { title: "Assamese", value: "Assamese" },
    { title: "Bengali", value: "Bengali" },
    { title: "Manipuri", value: "Manipuri" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];  

export const NagalandData = [
    { title: "Bengali", value: "Bengali" },
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Music", value: "Music" },
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const OdishaData = [
    { title: "Odia", value: "Odia" },
    { title: "Bengali", value: "Bengali" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Urdu", value: "Urdu" },
    { title: "Telugu", value: "Telugu" },
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const PunjabData = [
    { title: "Punjabi", value: "Punjabi" },
    { title: "Urdu", value: "Urdu" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const RajasthanData = [
    { title: "Hindi", value: "Hindi" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    // { title: "Science", value: "Science" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Music", value: "Music" },
    { title: "Computer Science", value: "Computer Science" },
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const TelanganaData = [
    { title: "Telugu", value: "Telugu" },
    { title: "Urdu", value: "Urdu" },
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Oriya", value: "Oriya" },
    { title: "Tamil", value: "Tamil"},
    { title: "Kannada", value: "Kannada"},
    { title: "Marathi", value: "Marathi"},
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Music", value: "Music" },
    { title: "Computer Science", value: "Computer Science" },
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const TNData = [
    { title: "Tamil", value: "Tamil"},
    { title: "Hindi", value: "Hindi" },
    { title: "English", value: "English" },
    { title: "Kannada", value: "Kannada"},
    { title: "Sanskrit", value: "Sanskrit" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const UPData = [
    { title: "Hindi", value: "Hindi" },
    { title: "Urdu", value: "Urdu" },
    { title: "Gujarati", value: "Gujarati"},
    { title: "Punjabi", value: "Punjabi"},
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Physical Education", value: "Physical Education" },
    { title: "Environmental Studies", value: "Environmental Studies"},
];

export const WBData = [
    { title: "Bengali", value: "Bengali"},
    { title: "Hindi", value: "Hindi" },
    { title: "Urdu", value: "Urdu" },
    { title: "Nepali", value: "Nepali"},
    { title: "Arabic", value: "Arabic"},
    { title: "English", value: "English" },
    { title: "Mathematics", value: "Mathematics" },
    { title: "Physics", value: "Physics" },
    { title: "Chemistry", value: "Chemistry" },
    { title: "Biology", value: "Biology" },
    { title: "Social Studies", value: "Social Studies"},
    { title: "Computer Science", value: "Computer Science"},
    { title: "Environmental Studies", value: "Environmental Studies"},
    { title: "Business Studies", value: "Business Studies"},
    { title: "Health & Physical Education", value: "Health & Physical Education"},
];

export const StateData = [
    { title: "Any Indian", value: "Any Indian"},
    { title: "Andhra pradesh", value: "Andhra pradesh"},
    { title: "Assam", value: "Assam"},
    { title: "Chattisgarh", value: "Chattisgarh"},
    { title: "Gujarat", value: "Gujarat"},
    { title: "Haryana", value: "Haryana"},
    { title: "Himachal Pradesh", value: "Himachal Pradesh"},
    { title: "Jharkhand", value: "Jharkhand"},
    { title: "Karnataka", value: "Karnataka"},
    { title: "Kerala", value: "Kerala"},
    { title: "Madhya Pradesh", value: "Madhya Pradesh"},
    { title: "Maharashtra", value: "Maharashtra"},
    { title: "Manipur", value: "Manipur"},
    { title: "Meghalaya", value: "Meghalaya"},
    { title: "Mizoram", value: "Mizoram"},
    { title: "Nagaland", value: "Nagaland"},
    { title: "Odisha", value: "Odisha"},
    { title: "Punjab", value: "Punjab"},
    { title: "Rajasthan", value: "Rajasthan"},
    { title: "Telangana", value: "Telangana"},
    { title: "Tamil Nadu", value: "Tamil Nadu"},
    { title: "Uttar Pradesh", value: "Uttar Pradesh"},
    { title: "West Bengal", value: "West Bengal"},
];